# Generated by Django 5.0.1 on 2024-04-04 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_location',
            name='location_latitude',
        ),
        migrations.RemoveField(
            model_name='tbl_location',
            name='location_longitude',
        ),
        migrations.RemoveField(
            model_name='tbl_location',
            name='location_pincode',
        ),
        migrations.CreateModel(
            name='tbl_route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_distance', models.CharField(max_length=50)),
                ('route_name', models.CharField(max_length=50)),
                ('from_location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_location_id1', to='Admin.tbl_location')),
                ('to_location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_location_id1', to='Admin.tbl_location')),
            ],
        ),
    ]
