# Generated by Django 5.0.1 on 2024-04-05 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_remove_tbl_location_location_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_route',
            name='from_location_id',
        ),
        migrations.RemoveField(
            model_name='tbl_route',
            name='route_distance',
        ),
        migrations.RemoveField(
            model_name='tbl_route',
            name='to_location_id',
        ),
        migrations.CreateModel(
            name='tbl_points',
            fields=[
                ('points_id', models.AutoField(primary_key=True, serialize=False)),
                ('points_distance', models.CharField(max_length=50)),
                ('points_name', models.CharField(max_length=50)),
                ('points_order', models.CharField(max_length=50)),
                ('from_location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_location_id1', to='Admin.tbl_location')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_route')),
                ('to_location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_location_id1', to='Admin.tbl_location')),
            ],
        ),
    ]
