# Generated by Django 5.0.1 on 2024-04-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_remove_tbl_points_points_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_points',
            name='points_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
