# Generated by Django 5.0.1 on 2024-04-28 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_points_points_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_points',
            name='from_location_id',
        ),
        migrations.RemoveField(
            model_name='tbl_points',
            name='to_location_id',
        ),
        migrations.AddField(
            model_name='tbl_points',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_location'),
        ),
    ]
