# Generated by Django 5.0.1 on 2024-04-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_remove_tbl_points_from_location_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_points',
            name='points_name',
        ),
    ]
