# Generated by Django 5.0.3 on 2024-03-30 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_driver_license',
            fields=[
                ('driver_license_front_photo', models.FileField(upload_to='Files/')),
                ('driver_license_back_photo', models.FileField(upload_to='Files/')),
                ('driver_license_date', models.CharField(max_length=50)),
                ('driver_license_exp_date', models.CharField(max_length=50)),
                ('driver_license_badge_exp_date', models.CharField(max_length=50)),
                ('driver_license_class', models.CharField(max_length=50)),
                ('driver_license_number', models.CharField(max_length=50)),
                ('driver_license_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_driver')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_transport_update',
            fields=[
                ('transport_update_id', models.AutoField(primary_key=True, serialize=False)),
                ('transport_update_datetime', models.CharField(max_length=50)),
                ('transport_update_location', models.CharField(max_length=50)),
                ('transport_update_status', models.IntegerField(default=0)),
                ('transport_shedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.tbl_transport_shedule')),
            ],
        ),
    ]
