# Generated by Django 5.0.1 on 2024-03-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_driver_license',
            name='driver_license_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbl_transport_update',
            name='transport_update_datetime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
