# Generated by Django 5.0.1 on 2024-04-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0002_alter_tbl_driver_license_driver_license_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_transport_update',
            old_name='transport_update_location',
            new_name='transport_update_latitude',
        ),
        migrations.RemoveField(
            model_name='tbl_transport_update',
            name='transport_update_status',
        ),
        migrations.AddField(
            model_name='tbl_transport_update',
            name='transport_update_longitude',
            field=models.CharField(default=6, max_length=50),
            preserve_default=False,
        ),
    ]
