# Generated by Django 5.0.1 on 2024-04-04 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_remove_tbl_transport_shedule_transport_amount'),
        ('Driver', '0004_delete_tbl_transport_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_transport_update',
            fields=[
                ('transport_update_id', models.AutoField(primary_key=True, serialize=False)),
                ('transport_update_datetime', models.DateField(auto_now_add=True)),
                ('transport_update_latitude', models.CharField(max_length=50)),
                ('transport_update_longitude', models.CharField(max_length=50)),
                ('transport_shedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.tbl_transport_shedule')),
            ],
        ),
    ]
