# Generated by Django 5.0.3 on 2024-03-30 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
        ('Guest', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_company_driver',
            fields=[
                ('company_driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_driver_status', models.IntegerField(default=0)),
                ('company_driver_date', models.CharField(max_length=50)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_driver')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_driver_request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.CharField(max_length=50)),
                ('request_status', models.CharField(default=0, max_length=10)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_driver')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_chase_no', models.CharField(max_length=50)),
                ('vehicle_reg_no', models.CharField(max_length=50)),
                ('vehicle_insurance_date', models.CharField(max_length=50)),
                ('vehicle_insurance_exp', models.CharField(max_length=50)),
                ('vehicle_status', models.PositiveIntegerField(default=0)),
                ('vehicle_detailes', models.CharField(max_length=100)),
                ('vehicle_name', models.CharField(max_length=50)),
                ('vehicle_amount', models.CharField(max_length=50)),
                ('vehicle_capacity', models.CharField(max_length=50)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company')),
                ('vehiclesubtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_vehiclesubtype')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_transport_shedule',
            fields=[
                ('transport_shedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('transport_shedule_date', models.CharField(max_length=50)),
                ('transport_shedule_status', models.IntegerField(default=0)),
                ('transport_amount', models.PositiveIntegerField()),
                ('driver_1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_1_id', to='Guest.tbl_driver')),
                ('driver_2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_2_id', to='Guest.tbl_driver')),
                ('transport_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_transport_request')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.tbl_vehicle')),
            ],
        ),
    ]
