# Generated by Django 5.0.1 on 2024-04-01 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_alter_tbl_company_driver_company_driver_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_transport_shedule',
            name='transport_amount',
        ),
    ]
