# Generated by Django 5.0.3 on 2024-03-30 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('company_contact', models.CharField(max_length=50)),
                ('company_email', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=50)),
                ('company_doj', models.CharField(max_length=50)),
                ('company_since', models.CharField(max_length=50)),
                ('company_proof', models.FileField(upload_to='Files/')),
                ('company_logo', models.FileField(upload_to='Files/')),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_email', models.CharField(max_length=50)),
                ('owner_contact', models.CharField(max_length=50)),
                ('company_status', models.IntegerField(default=0)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_location')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=50)),
                ('driver_primary_contact', models.CharField(max_length=50)),
                ('driver_secondary_contact', models.CharField(max_length=50)),
                ('driver_email', models.CharField(max_length=50)),
                ('driver_proof', models.FileField(upload_to='Files/')),
                ('driver_photo', models.FileField(upload_to='Files/')),
                ('driver_dob', models.CharField(max_length=50)),
                ('driver_doj', models.CharField(max_length=50)),
                ('driver_password', models.CharField(max_length=50)),
                ('driver_address', models.CharField(max_length=50)),
                ('driver_expirence', models.CharField(max_length=50)),
                ('driver_status', models.IntegerField(default=0)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_location')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_dob', models.CharField(max_length=50)),
                ('user_doj', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_aadhar_number', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_status', models.IntegerField(default=0)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_location')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_content', models.CharField(max_length=50)),
                ('feedback_date', models.CharField(max_length=50)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_driver')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_content', models.CharField(max_length=50)),
                ('complaint_date', models.CharField(max_length=50)),
                ('complaint_status', models.IntegerField(default=0)),
                ('complaint_reply', models.CharField(default='Not Yet Reply', max_length=50)),
                ('complaint_reply_date', models.CharField(max_length=50)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company')),
                ('complainttype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_complainttype')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_driver')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
