# Generated by Django 5.0.3 on 2024-03-30 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_transport_request',
            fields=[
                ('transport_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('transport_request_description', models.CharField(max_length=50)),
                ('transport_request_date', models.CharField(max_length=50)),
                ('transport_request_qty', models.CharField(max_length=50)),
                ('transport_request_for_date', models.CharField(max_length=50)),
                ('transport_request_status', models.PositiveIntegerField(default=0)),
                ('transport_request_reply', models.CharField(default='0', max_length=50)),
                ('delivery_time', models.CharField(max_length=50)),
                ('delivery_date', models.CharField(max_length=50)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company')),
                ('from_location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_location_id', to='Admin.tbl_location')),
                ('to_location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_location_id', to='Admin.tbl_location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
