# Generated by Django 5.0.1 on 2024-03-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_transport_request',
            name='transport_request_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
